# Open up firewall ports for mailcow
- name: Open firewall ports for mailcow
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled 
  loop: "{{ mail_ports }}"
  when: ansible_facts['os_family'] == 'RedHat'
  tags: mailcow

- name: Git Clone mailcow repository
  ansible.builtin.git:
    repo: "{{ mailcow_repo }}"
    dest: /opt/mailcow-dockerized
    version: master
    force: true
  when: inventory_hostname in groups['mail']
  tags: mailcow

- name: Create mailcow configuration file
  ansible.builtin.template:
    src: mailcow.conf.jinja2
    dest: /opt/mailcow-dockerized/mailcow.conf
  when: inventory_hostname in groups['mail']
  tags: mailcow